### ISSUE TITLE
Things to be done before the milestone submission

### ISSUE THREAD

**Issue by TengMCing** [TengMCing/lineup_residual_diagnostics#1]
Milestone report
- [x] Finish the thesis structure
- [ ]  If possible, use the short title for pages
- [x] Mention the purpose of the first project is to collect data for training/testing the model
- [ ] Include the mosaic plot in the report
- [ ] Introduction part, improve the justification of the graphical approach

Online form
- [x] Fill in the form 

Attached paper
- [ ] Consistent case for words like "non-linearity" in figure and table
- [x] Consistent case for reference
- [ ] Spell check

Attached appendix
- [ ] Include check_allocation_for_subject.png? (perhaps later)
- [ ] C1 needs more clarification

Presentation
- [ ] Use paper headings as slide headings
- [ ] 2/3 time for the first paper
- [ ] After finishing talking about the paper, what to do next, timetable
